name: hyperscan
on:
  push:
    paths:
      - hyperscan/**
  pull_request:
    paths:
      - hyperscan/**
  workflow_dispatch:
env:
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
jobs:
  linux-x86_64:
    runs-on: ubuntu-16.04
    container: centos:7
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  macosx-x86_64:
    runs-on: macos-10.15
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
  windows-x86_64:
    runs-on: windows-2019
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
  redeploy:
    needs: [linux-x86_64, macosx-x86_64, windows-x86_64]
    runs-on: ubuntu-16.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/redeploy@actions
