name: llvm
on:
  push:
    paths:
      - llvm/**
      - .github/workflows/llvm.yml
  pull_request:
    paths:
      - llvm/**
      - .github/workflows/llvm.yml
  workflow_dispatch:
env:
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
#  linux-armhf:
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
  linux-arm64:
    runs-on: ubuntu-22.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
#  linux-ppc64le:
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
#  linux-x86:
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
  linux-x86_64:
    runs-on: ubuntu-22.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
  macosx-arm64:
    runs-on: macos-15-intel
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
  macosx-x86_64:
    runs-on: macos-15-intel
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
  windows-arm64:
    runs-on: windows-11-arm
    env:
      BUILD_DIR: C:\build
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
#  windows-x86:
#    runs-on: windows-2022
#    env:
#      BUILD_DIR: C:\build
#    steps:
#      - uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
  windows-x86_64:
    runs-on: windows-2022
    env:
      BUILD_DIR: C:\build
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
  platform:
#    needs: [linux-armhf, linux-arm64, linux-ppc64le, linux-x86, linux-x86_64, macosx-arm64, macosx-x86_64, windows-x86, windows-x86_64]
    needs: [linux-arm64, linux-x86_64, macosx-arm64, macosx-x86_64, windows-arm64, windows-x86_64]
    runs-on: ubuntu-22.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/redeploy@actions
  samples:
    needs: platform
    strategy:
      matrix:
#        os: [ubuntu-22.04, macos-13, windows-11-arm, windows-2022]
        os: [ubuntu-22.04, macos-15, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          mvn -B -U -e clean compile exec:java -Pfactorial
          mvn exec:java -Pemit-bitcode
          mvn exec:java -Pevaluate-bitcode
          mvn exec:java -Porcjit
        working-directory: llvm/samples/llvm
