name: nvcodec
on:
  push:
    paths:
      - nvcodec/**
      - .github/workflows/nvcodec.yml
  pull_request:
    paths:
      - nvcodec/**
      - .github/workflows/nvcodec.yml
  workflow_dispatch:
env:
  CI_DEPLOY_NEED_CUDA: 1
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  linux-arm64:
    runs-on: ubuntu-22.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
#  linux-ppc64le:
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
  linux-x86_64:
    runs-on: ubuntu-22.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
  windows-x86_64:
    runs-on: windows-2022
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
  platform:
#    needs: [linux-arm64, linux-ppc64le, linux-x86_64, windows-x86_64]
    needs: [linux-arm64, linux-x86_64, windows-x86_64]
    runs-on: ubuntu-22.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/redeploy@actions
