name: tensorflow-lite
on:
  push:
    paths:
      - tensorflow-lite/**
      - .github/workflows/tensorflow-lite.yml
  pull_request:
    paths:
      - tensorflow-lite/**
      - .github/workflows/tensorflow-lite.yml
  workflow_dispatch:
env:
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
#  android-arm:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu
  android-arm64:
    runs-on: ubuntu-20.04
    steps:
      - uses: barrypitman/javacpp-presets/.github/actions/deploy-ubuntu
#  android-x86:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: barrypitman/javacpp-presets/.github/actions/deploy-ubuntu
  android-x86_64:
    runs-on: ubuntu-20.04
    steps:
      - uses: barrypitman/javacpp-presets/.github/actions/deploy-ubuntu
#  linux-armhf:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: barrypitman/javacpp-presets/.github/actions/deploy-ubuntu
  linux-arm64:
    runs-on: ubuntu-20.04
    steps:
      - uses: barrypitman/javacpp-presets/.github/actions/deploy-ubuntu
#  linux-x86:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: barrypitman/javacpp-presets/.github/actions/deploy-ubuntu
  linux-x86_64:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ext:
          - '-gpu'
          - ''
    steps:
      - uses: barrypitman/javacpp-presets/.github/actions/deploy-ubuntu
  macosx-x86_64:
    runs-on: macos-11
    steps:
      - uses: barrypitman/javacpp-presets/.github/actions/deploy-macosx
  windows-x86_64:
    runs-on: windows-2019
    steps:
      - uses: barrypitman/javacpp-presets/.github/actions/deploy-windows
  redeploy:
#    needs: [android-arm, android-arm64, android-x86, android-x86_64, linux-armhf, linux-arm64, linux-x86, linux-x86_64, macosx-x86_64, windows-x86_64]
    needs: [android-arm64, android-x86_64, linux-arm64, linux-x86_64, macosx-x86_64, windows-x86_64]
    runs-on: ubuntu-20.04
    steps:
      - uses: barrypitman/javacpp-presets/.github/actions/redeploy

