name: tensorflow
on:
  push:
    paths:
      - tensorflow/**
  pull_request:
    paths:
      - tensorflow/**
  workflow_dispatch:
env:
  CI_DEPLOY_NEED_BAZEL: 1
  CI_DEPLOY_NEED_CUDA: 1
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  android-arm:
    runs-on: ubuntu-18.04
    container: centos:7
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  android-arm64:
    runs-on: ubuntu-18.04
    container: centos:7
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  android-x86:
    runs-on: ubuntu-18.04
    container: centos:7
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  android-x86_64:
    runs-on: ubuntu-18.04
    container: centos:7
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  linux-x86:
    runs-on: ubuntu-18.04
    container: centos:7
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  linux-x86_64:
    runs-on: ubuntu-18.04
    container: centos:7
    strategy:
      matrix:
        ext: ["", -gpu]
#        ext: ["", -gpu, -python, -python-gpu]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  macosx-x86_64:
    runs-on: macos-10.15
#    strategy:
#      matrix:
#        ext: ["", -gpu, -python, -python-gpu]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
  windows-x86_64:
    runs-on: windows-2019
    strategy:
      matrix:
        ext: ["", -gpu]
#        ext: ["", -gpu, -python, -python-gpu]
    steps:
      - uses: al-cheb/configure-pagefile-action@v1.2
        with:
          minimum-size: 16GB
          maximum-size: 32GB
          disk-root: "C:"
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
  redeploy:
    needs: [android-arm, android-arm64, android-x86, android-x86_64, linux-x86, linux-x86_64, macosx-x86_64, windows-x86_64]
    runs-on: ubuntu-18.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/redeploy@actions
