name: tvm
on:
  push:
    paths:
      - tvm/**
  pull_request:
    paths:
      - tvm/**
  workflow_dispatch:
env:
  CI_DEPLOY_NEED_CUDA: 1
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  linux-x86_64:
    runs-on: ubuntu-18.04
    container: centos:7
    strategy:
      matrix:
        ext: ["", -gpu]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
  macosx-x86_64:
    runs-on: macos-10.15
#    strategy:
#      matrix:
#        ext: ["", -gpu]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
  windows-x86_64:
    runs-on: windows-2019
    strategy:
      matrix:
        ext: ["", -gpu]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
  redeploy:
    needs: [linux-x86_64, macosx-x86_64, windows-x86_64]
    runs-on: ubuntu-18.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/redeploy@actions
